import { KeyBtn } from './KeyBtn';

export const keys = [
  new KeyBtn('Backquote', '`', '~', '\'', '~'),
  new KeyBtn('Digit1', '1', '!', '1', '!'),
  new KeyBtn('Digit2', '2', '@', '2', '"'),
  new KeyBtn('Digit3', '3', '#', '3', '№'),
  new KeyBtn('Digit4', '4', '$', '4', '%'),
  new KeyBtn('Digit5', '5', '%', '5', ':'),
  new KeyBtn('Digit6', '6', '^', '6', ','),
  new KeyBtn('Digit7', '7', '&', '7', '.'),
  new KeyBtn('Digit8', '8', '*', '8', ';'),
  new KeyBtn('Digit9', '9', '(', '9', '('),
  new KeyBtn('Digit0', '0', ')', '0', ')'),
  new KeyBtn('Minus', '-', '_', '-', '_'),
  new KeyBtn('Equal', '=', '+', '=', '+'),
  new KeyBtn('Backspace', 'delete', 'delete', 'delete', 'delete'),
  new KeyBtn('Tab', 'tab', 'tab', 'tab', 'tab'),
  new KeyBtn('KeyQ', 'Q', 'Q', 'Й', 'Й'),
  new KeyBtn('KeyW', 'W', 'W', 'Ц', 'Ц'),
  new KeyBtn('KeyE', 'E', 'E', 'У', 'У'),
  new KeyBtn('KeyR', 'R', 'R', 'К', 'К'),
  new KeyBtn('KeyT', 'T', 'T', 'Е', 'Е'),
  new KeyBtn('KeyY', 'Y', 'Y', 'Н', 'Н'),
  new KeyBtn('KeyU', 'U', 'U', 'Г', 'Г'),
  new KeyBtn('KeyI', 'I', 'I', 'Ш', 'Ш'),
  new KeyBtn('KeyO', 'O', 'O', 'Щ', 'Щ'),
  new KeyBtn('KeyP', 'P', 'P', 'З', 'З'),
  new KeyBtn('BracketLeft', '[', '{', 'Х', 'Х'),
  new KeyBtn('BracketRight', ']', '}', 'Ї', 'Ї'),
  new KeyBtn('Backslash', '\\', '|', 'Ґ', 'Ґ'),
  new KeyBtn('CapsLock', 'caps lock', 'caps lock', 'caps lock', 'caps lock'),
  new KeyBtn('KeyA', 'A', 'A', 'Ф', 'Ф'),
  new KeyBtn('KeyS', 'S', 'S', 'И', 'И'),
  new KeyBtn('KeyD', 'D', 'D', 'В', 'В'),
  new KeyBtn('KeyF', 'F', 'F', 'А', 'А'),
  new KeyBtn('KeyG', 'G', 'G', 'П', 'П'),
  new KeyBtn('KeyH', 'H', 'H', 'Р', 'Р'),
  new KeyBtn('KeyJ', 'J', 'J', 'О', 'О'),
  new KeyBtn('KeyK', 'K', 'K', 'Л', 'Л'),
  new KeyBtn('KeyL', 'L', 'L', 'Д', 'Д'),
  new KeyBtn('Semicolon', ';', ':', 'Ж', 'Ж'),
  new KeyBtn('Quote', '\'', '"', 'Є', 'Є'),
  new KeyBtn('Enter', 'return', 'return', 'return', 'return'),
  new KeyBtn('ShiftLeft', 'shift', 'shift', 'shift', 'shift'),
  new KeyBtn('KeyZ', 'Z', 'Z', 'Я', 'Я'),
  new KeyBtn('KeyX', 'X', 'X', 'Ч', 'Ч'),
  new KeyBtn('KeyC', 'C', 'C', 'С', 'С'),
  new KeyBtn('KeyV', 'V', 'V', 'М', 'М'),
  new KeyBtn('KeyB', 'B', 'B', 'І', 'І'),
  new KeyBtn('KeyN', 'N', 'N', 'Т', 'Т'),
  new KeyBtn('KeyM', 'M', 'M', 'Ь', 'Ь'),
  new KeyBtn('KeyM', ',', '<', 'Б', 'Б'),
  new KeyBtn('KeyM', '.', '>', 'Ю', 'Ю'),
  new KeyBtn('KeyM', '/', '?', '/', '?'),
  new KeyBtn('ArrowUp', '▲', '▲', '▲', '▲'),
  new KeyBtn('ShiftRight', 'shift', 'shift', 'shift', 'shift'),
  new KeyBtn('Fn', 'fn', 'fn', 'fn', 'fn'),
  new KeyBtn('ControlLeft', 'ctrl', 'ctrl', 'ctrl', 'ctrl'),
  new KeyBtn('AltLeft', 'alt', 'alt', 'alt', 'alt'),
  new KeyBtn('MetaLeft', '⌘', '⌘', '⌘', '⌘'),
  new KeyBtn('Space', ' ', ' ', ' ', ' '),
  new KeyBtn('MetaRight', '⌘', '⌘', '⌘', '⌘'),
  new KeyBtn('AltRight', 'alt', 'alt', 'alt', 'alt'),
  new KeyBtn('ArrowLeft', '◀', '◀', '◀', '◀'),
  new KeyBtn('ArrowDown', '▼', '▼', '▼', '▼'),
  new KeyBtn('ArrowRight', '▶', '▶', '▶', '▶'),
];

export const rowNumbers = [0, 14, 14, 13, 13, 10];
