import { KeyBtn } from './KeyBtn';

export const keys = [
  new KeyBtn('Backquote', '`', '~', '\'', '~', 'key-btn_special'),
  new KeyBtn('Digit1', '1', '!', '1', '!', 'key-btn_digit'),
  new KeyBtn('Digit2', '2', '@', '2', '"', 'key-btn_digit'),
  new KeyBtn('Digit3', '3', '#', '3', '№', 'key-btn_digit'),
  new KeyBtn('Digit4', '4', '$', '4', '%', 'key-btn_digit'),
  new KeyBtn('Digit5', '5', '%', '5', ':', 'key-btn_digit'),
  new KeyBtn('Digit6', '6', '^', '6', ',', 'key-btn_digit'),
  new KeyBtn('Digit7', '7', '&', '7', '.', 'key-btn_digit'),
  new KeyBtn('Digit8', '8', '*', '8', ';', 'key-btn_digit'),
  new KeyBtn('Digit9', '9', '(', '9', '(', 'key-btn_digit'),
  new KeyBtn('Digit0', '0', ')', '0', ')', 'key-btn_digit'),
  new KeyBtn('Minus', '-', '_', '-', '_', 'key-btn_digit'),
  new KeyBtn('Equal', '=', '+', '=', '+', 'key-btn_digit'),
  new KeyBtn('Backspace', '✘', '✘', '✘', '✘', 'key-btn_special'),
  new KeyBtn('Tab', '➠', '➠', '➠', '➠', 'key-btn_special', '\t'),
  new KeyBtn('KeyQ', 'Q', 'Q', 'Й', 'Й'),
  new KeyBtn('KeyW', 'W', 'W', 'Ц', 'Ц'),
  new KeyBtn('KeyE', 'E', 'E', 'У', 'У'),
  new KeyBtn('KeyR', 'R', 'R', 'К', 'К'),
  new KeyBtn('KeyT', 'T', 'T', 'Е', 'Е'),
  new KeyBtn('KeyY', 'Y', 'Y', 'Н', 'Н'),
  new KeyBtn('KeyU', 'U', 'U', 'Г', 'Г'),
  new KeyBtn('KeyI', 'I', 'I', 'Ш', 'Ш'),
  new KeyBtn('KeyO', 'O', 'O', 'Щ', 'Щ'),
  new KeyBtn('KeyP', 'P', 'P', 'З', 'З'),
  new KeyBtn('BracketLeft', '[', '{', 'Х', 'Х'),
  new KeyBtn('BracketRight', ']', '}', 'Ї', 'Ї'),
  new KeyBtn('Backslash', '\\', '|', 'Ґ', 'Ґ', 'key-btn_special'),
  new KeyBtn('CapsLock', '⏏', '⏏', '⏏', '⏏', 'key-btn_special'),
  new KeyBtn('KeyA', 'A', 'A', 'Ф', 'Ф'),
  new KeyBtn('KeyS', 'S', 'S', 'И', 'И'),
  new KeyBtn('KeyD', 'D', 'D', 'В', 'В'),
  new KeyBtn('KeyF', 'F', 'F', 'А', 'А'),
  new KeyBtn('KeyG', 'G', 'G', 'П', 'П'),
  new KeyBtn('KeyH', 'H', 'H', 'Р', 'Р'),
  new KeyBtn('KeyJ', 'J', 'J', 'О', 'О'),
  new KeyBtn('KeyK', 'K', 'K', 'Л', 'Л'),
  new KeyBtn('KeyL', 'L', 'L', 'Д', 'Д'),
  new KeyBtn('Semicolon', ';', ':', 'Ж', 'Ж'),
  new KeyBtn('Quote', '\'', '"', 'Є', 'Є'),
  new KeyBtn('Enter', '✔', '✔', '✔', '✔', 'key-btn_special key-btn_enter', '\n'),
  new KeyBtn('ShiftLeft', '⇵', '⇵', '⇵', '⇵', 'key-btn_special'),
  new KeyBtn('KeyZ', 'Z', 'Z', 'Я', 'Я'),
  new KeyBtn('KeyX', 'X', 'X', 'Ч', 'Ч'),
  new KeyBtn('KeyC', 'C', 'C', 'С', 'С'),
  new KeyBtn('KeyV', 'V', 'V', 'М', 'М'),
  new KeyBtn('KeyB', 'B', 'B', 'І', 'І'),
  new KeyBtn('KeyN', 'N', 'N', 'Т', 'Т'),
  new KeyBtn('KeyM', 'M', 'M', 'Ь', 'Ь'),
  new KeyBtn('KeyM', ',', '<', 'Б', 'Б'),
  new KeyBtn('KeyM', '.', '>', 'Ю', 'Ю'),
  new KeyBtn('KeyM', '/', '?', '/', '?'),
  new KeyBtn('ArrowUp', '▲', '▲', '▲', '▲', 'key-btn_special key-btn_arrow'),
  new KeyBtn('ShiftRight', '⇵', '⇵', '⇵', '⇵', 'key-btn_special'),
  new KeyBtn('Fn', 'fn', 'fn', 'fn', 'fn', 'key-btn_special'),
  new KeyBtn('ControlLeft', 'ctrl', 'ctrl', 'ctrl', 'ctrl', 'key-btn_special'),
  new KeyBtn('AltLeft', 'alt', 'alt', 'alt', 'alt', 'key-btn_special'),
  new KeyBtn('MetaLeft', '⌘', '⌘', '⌘', '⌘', 'key-btn_special'),
  new KeyBtn('Space', '┉', '┉', '┉', '┉', 'key-btn_space', ' '),
  new KeyBtn('MetaRight', '⌘', '⌘', '⌘', '⌘', 'key-btn_special'),
  new KeyBtn('AltRight', 'alt', 'alt', 'alt', 'alt', 'key-btn_special'),
  new KeyBtn('ArrowLeft', '◀', '◀', '◀', '◀', 'key-btn_special key-btn_arrow'),
  new KeyBtn('ArrowDown', '▼', '▼', '▼', '▼', 'key-btn_special key-btn_arrow'),
  new KeyBtn('ArrowRight', '▶', '▶', '▶', '▶', 'key-btn_special key-btn_arrow'),
];

export const rowNumbers = [14, 14, 13, 13, 10];
